// <auto-generated />
using System;
using GenealogyWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenealogyWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260518031502_AddPersonGeneration")]
    partial class AddPersonGeneration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GenealogyWeb.Models.Genealogy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompiledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Genealogies");
                });

            modelBuilder.Entity("GenealogyWeb.Models.GenealogyUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("GenealogyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("InvitedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("GenealogyId", "UserId")
                        .IsUnique();

                    b.ToTable("GenealogyUsers");
                });

            modelBuilder.Entity("GenealogyWeb.Models.Marriage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DivorcedAtYear")
                        .HasColumnType("int");

                    b.Property<Guid>("GenealogyId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("MarriedAtYear")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<Guid>("SpouseAId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SpouseBId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GenealogyId");

                    b.HasIndex("SpouseAId");

                    b.HasIndex("SpouseBId");

                    b.ToTable("Marriages", t =>
                        {
                            t.HasCheckConstraint("CK_Marriage_DifferentSpouses", "`SpouseAId` <> `SpouseBId`");

                            t.HasCheckConstraint("CK_Marriage_DivorceAfterWedding", "`DivorcedAtYear` IS NULL OR `MarriedAtYear` IS NULL OR `DivorcedAtYear` >= `MarriedAtYear`");
                        });
                });

            modelBuilder.Entity("GenealogyWeb.Models.ParentChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ChildId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GenealogyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("ParentId");

                    b.HasIndex("GenealogyId", "ParentId");

                    b.ToTable("ParentChildren", t =>
                        {
                            t.HasCheckConstraint("CK_ParentChildren_NotSelf", "`ParentId` <> `ChildId`");
                        });
                });

            modelBuilder.Entity("GenealogyWeb.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Bio")
                        .HasColumnType("longtext");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeathYear")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<Guid>("GenealogyId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Generation")
                        .HasColumnType("int");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("GenealogyId", "GivenName");

                    b.ToTable("Persons", t =>
                        {
                            t.HasCheckConstraint("CK_Person_BirthBeforeDeath", "`BirthYear` IS NULL OR `DeathYear` IS NULL OR `BirthYear` <= `DeathYear`");
                        });
                });

            modelBuilder.Entity("GenealogyWeb.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GenealogyWeb.Models.Genealogy", b =>
                {
                    b.HasOne("GenealogyWeb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenealogyWeb.Models.GenealogyUser", b =>
                {
                    b.HasOne("GenealogyWeb.Models.Genealogy", null)
                        .WithMany()
                        .HasForeignKey("GenealogyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenealogyWeb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GenealogyWeb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenealogyWeb.Models.Marriage", b =>
                {
                    b.HasOne("GenealogyWeb.Models.Genealogy", null)
                        .WithMany()
                        .HasForeignKey("GenealogyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenealogyWeb.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("SpouseAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenealogyWeb.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("SpouseBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenealogyWeb.Models.ParentChild", b =>
                {
                    b.HasOne("GenealogyWeb.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenealogyWeb.Models.Genealogy", null)
                        .WithMany()
                        .HasForeignKey("GenealogyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenealogyWeb.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenealogyWeb.Models.Person", b =>
                {
                    b.HasOne("GenealogyWeb.Models.Genealogy", null)
                        .WithMany()
                        .HasForeignKey("GenealogyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
